#! /usr/bin/php
<?php

	// Utils functions
	
	function getPromptEntry ($message, $hidden = false) {
		echo $message . "\n";
		$handle = fopen ("php://stdin","r");
		if($hidden) echo "\033[30;40m";
		$line = trim(fgets($handle));
		if($hidden) echo "\033[0m";
		fclose($handle);
		return $line;
	}
	
	if(empty($_SERVER['argv'][1])) {
		echo "Usage impulse [init] <project>\n";
		exit();
	}
	
	switch( $_SERVER['argv'][1] ){
		case "init":
			
			if(empty( $_SERVER['argv'][2] ) || !preg_match("/^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$/i", $_SERVER['argv'][2] )) {
				echo "Invalid project name\n";
				echo "Must be a domain ( ex: adjust.be )\n";
				exit();
			}
			
			$project = $_SERVER['argv'][2];
			
			$bower = json_decode(file_get_contents('bower.json'));
			$bower->name = $project;
			$bower->description = $project . " front-end";
				
			file_put_contents('bower.json', json_encode($bower, JSON_PRETTY_PRINT) );
			
			echo "Updating Bower.json\n";
						
			$package = json_decode(file_get_contents('package.json'));
			$package->name = $project;
			$package->description = $project . " front-end";
				
			file_put_contents('package.json', json_encode($package, JSON_PRETTY_PRINT) );
			
			echo "Updating Package.json\n";
			
			
				// Remove .git folder
				echo "Initialize git project\n";
				
				exec('rm -rf ./.git');	
				// init git
				exec('git init');
	
				echo "Updating project\n";
	
				passthru('sudo npm install gulp --save-dev');
				passthru('sudo npm install gulp-concat --save-dev');
				passthru('sudo npm install gulp-imagemin --save-dev');
				passthru('sudo npm install gulp-jshint --save-dev');
				passthru('sudo npm install gulp-minify --save-dev');
				passthru('sudo npm install gulp-sass --save-dev');
				passthru('sudo npm install gulp-postcss --save-dev');
				passthru('sudo npm install gulp-sourcemaps --save-dev');
				passthru('sudo npm install gulp-uglify --save-dev');
				passthru('sudo npm install gulp-connect-php --save-dev');
				passthru('sudo npm install autoprefixer --save-dev');
				passthru('sudo npm install cssnano --save-dev');
				passthru('sudo npm install browser-sync --save-dev');
				passthru('sudo npm install jshint --save-dev');
				passthru('sudo npm install jshint-stylish --save-dev');
				
				
				passthru('bower install font-awesome --save');
				passthru('bower install normalize-css --save');
				passthru('bower install jquery --save');
				
				if(!empty( $_SERVER['argv'][3] )) {
					switch(trim($_SERVER['argv'][3])) {
						case '--gulp':
							passthru('gulp');
							break;
					}
				}
				
			break;
			
		case "deploy" :
			
			function exitOnInvalidEnv() {
				echo "Invalid environnement\n";
				echo "Must be staging or production\n";
				exit();
			}
			
			if(empty( $_SERVER['argv'][2] )) {
				exitOnInvalidEnv();
			}
			
			$package = json_decode(file_get_contents('package.json'));
			$project = $package->name;
			
			if(empty(trim($project))) {
				echo "Invalid domain name\n";
				echo "Use impulse init first\n";
				exit();
			}
			
			$remote = exec("git remote -v | grep push");
			preg_match("/(https?:\/\/.*\.git)/i", $remote, $matches);

			if(empty($matches[1])) {
				echo "Invalid remote repository\n";
				echo "Push git project to remote server first\n";
				exit();
			};
			
			$repository 	= trim(strtolower($matches[1]));
			$isFramework	= is_dir( __DIR__ . '/public' );
			
			switch(trim($_SERVER['argv'][2])){
				case 'staging':
				
					$options = '';
					if( $isFramework ) $options .= ' --with-framework';
					
					$username = getPromptEntry("Enter your dev.adjust.be username :");
					
					$command = 'ssh ' . $username . '@dev.adjust.be "/usr/bin/adjtools -d staging --with-project ' . $project . ' --with-remote ' . $repository . $options . '"';
					passthru($command);
					
					break;
				default:
					exitOnInvalidEnv();
			}
			
			break;
		default:
			echo "Unknown command " . $_SERVER['argv'][1] . "\n";
			exit();
	}